name: Build "turnip"

on:
  workflow_dispatch:
  # schedule:
  # - cron: '30 0-23 * * *'

jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: alpha

      - name: Prepare environment
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt update
          sudo apt build-dep mesa -y
          # Install ccache to match your cross-file usage
          sudo apt install -y ccache

      - name: Execute build script
        run: bash ./turnip_builder.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-glcore-build-output
          path: mesa_glcore_workdir/output
